services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - influxdb-data:/var/lib/influxdb2
    environment:
      # See also: https://hub.docker.com/_/influxdb
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_ORG}
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_ADMIN_TOKEN}
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_BUCKET}

  device-hub:
    build:
      context: ../../
      dockerfile: projects/main/Dockerfile
    image: device-hub:latest
    cap_add:
      - SYS_TIME
    network_mode: host
    container_name: device-hub
    command: [
      "--http-port", "${DEVICE_HUB_HTTP_PORT}",
      "--cache-dir", "${DEVICE_HUB_CACHE_DIR}",
      "--log-path", "${DEVICE_HUB_LOG_PATH}",
      "--influxdb-url", "${INFLUXDB_URL}",
      "--influxdb-org", "${INFLUXDB_ORG}",
      "--influxdb-api-token", "${INFLUXDB_API_TOKEN}",
      "--influxdb-bucket", "${INFLUXDB_BUCKET}",
      "--mdns-browse-iface", "${DEVICE_HUB_MDNS_BROWSE_IFACE}",
      "--mdns-server-iface", "${DEVICE_HUB_MDNS_SERVER_IFACE}"
    ]
    volumes:
      - ${DEVICE_HUB_LOG_PATH}:${DEVICE_HUB_LOG_PATH}
      - ${DEVICE_HUB_CACHE_DIR}:${DEVICE_HUB_CACHE_DIR}
    depends_on:
      - influxdb

volumes:
  influxdb-data:
