name: Device-Hub

on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  build:
    runs-on: [ubuntu-latest, macos-latest, arm64-ubuntu]

    # https://github.com/marketplace/actions/golangci-lint#annotations
    permissions:
      # Required: allow read access to the content for analysis.
      contents: read
      # Optional: allow read access to pull request. Use with `only-new-issues` option.
      pull-requests: read
      # Optional: allow write access to checks to allow the action to annotate code in the PR.
      checks: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60
          only-new-issues: true
          args: ./...

      - name: Build application
        shell: bash
        run: |
          go mod download
          go build ./...
          go test ./... --race

          cd projects/main
          docker compose build
